# Generated by Django 4.1.7 on 2023-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='maintenance_category',
            field=models.ManyToManyField(to='services.maintenancecategory'),
        ),
    ]
