# Generated by Django 4.1.7 on 2023-03-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_maintenance_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='protocole',
            new_name='protocol',
        ),
    ]
