# Generated by Django 4.1.7 on 2023-03-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecategory',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar válvula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento')], max_length=3),
        ),
    ]
