# Generated by Django 4.1.7 on 2023-03-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('services', '0006_categoriamanutencao_servico_remove_service_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('TVM', 'Trocar válvula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_inico', models.DateField(null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocol', models.CharField(blank=True, max_length=52, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.cliente')),
                ('maintenance_category', models.ManyToManyField(to='services.maintenancecategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='categoria_manutencao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='CategoriaManutencao',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
