# Generated by Django 4.1.7 on 2023-03-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_maintenancecategory_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='data_inico',
            new_name='data_inicio',
        ),
    ]
