# Generated by Django 4.1.7 on 2023-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_data_inico_service_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
