# Generated by Django 4.1.7 on 2023-03-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_categoriamanutencao_servico_remove_service_cliente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaManutencao',
            new_name='MaintenanceCategory',
        ),
    ]
