# Generated by Django 4.1.7 on 2023-03-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('services', '0011_rename_categoriamanutencao_maintenancecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='Service',
        ),
    ]
