# Generated by Django 4.1.7 on 2023-03-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_rename_servico_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='categoria_manutencao',
            new_name='maintenance_category',
        ),
    ]
