# Generated by Django 4.1.7 on 2023-03-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_rename_categoria_manutencao_service_maintenance_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='identificador',
        ),
    ]
