# Generated by Django 4.1.7 on 2023-03-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_service_identificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='protocole',
            new_name='protocol',
        ),
    ]
