# Generated by Django 4.1.7 on 2023-03-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_rename_protocole_service_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancecategory',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar válcula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento'), ('TDP', 'Troca de pneu')], max_length=3),
        ),
    ]
