# Generated by Django 4.1.7 on 2023-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_service_identificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
